### ISSUE TITLE
text boards?

### ISSUE THREAD

**Issue by textboards** [FChannel0/FChannel-Server#66]
How about also adding in text only boards? A few chans have textboards and imageboards... both have their uses. Fchan handles text very fast... so I think textboards would be showcasing a strength of fchan, and also adding more depth to fchan instances.

**Comment by FChannel0** [comment]
This wouldnt be hard to implement. After some things gets cleaned up I dont see a reason to not have this as an option.

**Comment by ghost** [comment]
Cool! Just as an idea, could you just make an option to not show the file upload on some boards? That would make it an instant textboard. Oah and what THE Fchannel is going on here? I just found this...https://github.com/cag1439/feditext so that's kinda unusual. Edit/// For Fchan main branch, actually the option to post text without having to post an image would be nice, sometimes ppl have something worthwhile to say in a new thread and no image avail.

**Comment by ghost** [comment]
wow i did not notice you got rid of the redis dependency, that is awesome!! This board is the best golang ib out there.
